### ISSUE TITLE
Disable text selection

### ISSUE THREAD

**Issue by micahlt** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#19]
**Describe the feature you'd like**
Often I use Electron apps and notice that I can select text.  In some cases, this is useful.  However, most of the time it just adds to the feeling that I'm using a _website_, not a native app.  This app is similar.  I believe that you should _not_ be able to select text in this client to help create a more native feel.

**Describe alternatives you've considered**
This is, of course, a matter of opinion.  Some may prefer the ability to select.  Maybe this could even be added as a setting?

I'd be glad to work on this and submit a PR if that'd be helpful!

**Comment by Melvin-Abraham** [comment]
@micahlt This seems to be a reasonable feature. Contributions are more than welcome 😊.

One thing to take into consideration is that this option must be provided as a **setting** that can be toggled just so that it gives users more flexibility in choice...

**Comment by adel-sbeh** [comment]
```css
*{
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -webkit-user-drag: none;
  -khtml-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```
This should do the trick
